services:
      postgres_strapi_api:
        container_name: postgres_strapi_api
        hostname: postgres_strapi_api
        image: postgres
        restart: always
        environment:
          POSTGRES_PASSWORD: senha
          POSTGRES_DB: blog-strapi
          PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
          - ~/ .PostgressData/postgresonly/postgres_strapi_blog:/var/lib/postgresql/data/pgdata
        ports:
          - 5432:5432